"""empty message

Revision ID: 44c583578723
Revises: 9a75a9997dd8
Create Date: 2023-07-06 09:20:53.977068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c583578723'
down_revision = '9a75a9997dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('price2', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'price2')
    # ### end Alembic commands ###
