"""empty message

Revision ID: 61ca7f683d4c
Revises: 44c583578723
Create Date: 2023-07-24 10:17:18.350862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ca7f683d4c'
down_revision = '44c583578723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal', 'height')
    op.drop_column('animal', 'chip')
    op.drop_column('animal', 'price2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal', sa.Column('price2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('animal', sa.Column('chip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('animal', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
