"""empty message

Revision ID: 9a75a9997dd8
Revises: 
Create Date: 2023-06-27 15:15:10.234891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a75a9997dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_user_id', sa.Integer(), nullable=False),
    sa.Column('settings_user_name', sa.String(), nullable=False),
    sa.Column('settings_name', sa.String(), nullable=False),
    sa.Column('settings_type', sa.String(), nullable=False),
    sa.Column('settings_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertisement_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region_residence', sa.String(), nullable=True),
    sa.Column('country_residence', sa.String(), nullable=True),
    sa.Column('be_used_for_hu', sa.String(), nullable=True),
    sa.Column('be_used_for_en', sa.String(), nullable=True),
    sa.Column('be_used_for_de', sa.String(), nullable=True),
    sa.Column('be_used_for_fr', sa.String(), nullable=True),
    sa.Column('be_used_for_es', sa.String(), nullable=True),
    sa.Column('gender_hu', sa.String(), nullable=True),
    sa.Column('gender_en', sa.String(), nullable=True),
    sa.Column('gender_de', sa.String(), nullable=True),
    sa.Column('gender_fr', sa.String(), nullable=True),
    sa.Column('gender_es', sa.String(), nullable=True),
    sa.Column('color_hu', sa.String(), nullable=True),
    sa.Column('color_en', sa.String(), nullable=True),
    sa.Column('color_de', sa.String(), nullable=True),
    sa.Column('color_fr', sa.String(), nullable=True),
    sa.Column('color_es', sa.String(), nullable=True),
    sa.Column('brief_description', sa.String(), nullable=True),
    sa.Column('brief_description_detect_lang', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('description_detect_lang', sa.String(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('url_01', sa.String(), nullable=True),
    sa.Column('url_02', sa.String(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.FLOAT(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('worker_visibility', sa.String(), nullable=True),
    sa.Column('last_modification_user_id', sa.Integer(), nullable=True),
    sa.Column('last_modification_user_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('breed_registry', sa.String(), nullable=True),
    sa.Column('breed_registry_data', sa.String(), nullable=True),
    sa.Column('x_ray', sa.String(), nullable=True),
    sa.Column('x_ray_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('img_01', sa.String(), nullable=True),
    sa.Column('img_01_data', sa.String(), nullable=True),
    sa.Column('img_02', sa.String(), nullable=True),
    sa.Column('img_02_data', sa.String(), nullable=True),
    sa.Column('img_03', sa.String(), nullable=True),
    sa.Column('img_03_data', sa.String(), nullable=True),
    sa.Column('img_04', sa.String(), nullable=True),
    sa.Column('img_04_data', sa.String(), nullable=True),
    sa.Column('img_05', sa.String(), nullable=True),
    sa.Column('img_05_data', sa.String(), nullable=True),
    sa.Column('img_06', sa.String(), nullable=True),
    sa.Column('img_06_data', sa.String(), nullable=True),
    sa.Column('img_07', sa.String(), nullable=True),
    sa.Column('img_07_data', sa.String(), nullable=True),
    sa.Column('img_08', sa.String(), nullable=True),
    sa.Column('img_08_data', sa.String(), nullable=True),
    sa.Column('img_09', sa.String(), nullable=True),
    sa.Column('img_09_data', sa.String(), nullable=True),
    sa.Column('img_10', sa.String(), nullable=True),
    sa.Column('img_10_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('video_01', sa.String(), nullable=True),
    sa.Column('video_01_data', sa.String(), nullable=True),
    sa.Column('youtube_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_detect_lang', sa.String(), nullable=True),
    sa.Column('editing', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_detect_lang', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barion_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_request_id', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('vat', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('billing_url', sa.String(), nullable=True),
    sa.Column('account_type', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_user_id', sa.Integer(), nullable=False),
    sa.Column('category_user_name', sa.String(), nullable=False),
    sa.Column('name_hu', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_de', sa.String(), nullable=False),
    sa.Column('name_fr', sa.String(), nullable=False),
    sa.Column('name_es', sa.String(), nullable=False),
    sa.Column('gender_hu', sa.String(), nullable=False),
    sa.Column('gender_en', sa.String(), nullable=False),
    sa.Column('gender_de', sa.String(), nullable=False),
    sa.Column('gender_fr', sa.String(), nullable=False),
    sa.Column('gender_es', sa.String(), nullable=False),
    sa.Column('be_used_for_hu', sa.String(), nullable=True),
    sa.Column('be_used_for_en', sa.String(), nullable=True),
    sa.Column('be_used_for_de', sa.String(), nullable=True),
    sa.Column('be_used_for_fr', sa.String(), nullable=True),
    sa.Column('be_used_for_es', sa.String(), nullable=True),
    sa.Column('color_hu', sa.String(), nullable=True),
    sa.Column('color_en', sa.String(), nullable=True),
    sa.Column('color_de', sa.String(), nullable=True),
    sa.Column('color_fr', sa.String(), nullable=True),
    sa.Column('color_es', sa.String(), nullable=True),
    sa.Column('img_data', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_first_name', sa.String(), nullable=True),
    sa.Column('sender_last_name', sa.String(), nullable=True),
    sa.Column('sender_username', sa.String(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('host_first_name', sa.String(), nullable=True),
    sa.Column('host_last_name', sa.String(), nullable=True),
    sa.Column('host_username', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('received', sa.String(), nullable=True),
    sa.Column('sender_assistant', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('archive_sender_id', sa.Integer(), nullable=True),
    sa.Column('archive_host_id', sa.Integer(), nullable=True),
    sa.Column('two_sided_archiving', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_host_id'), 'messages', ['host_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant', sa.Integer(), nullable=True),
    sa.Column('notifications_01', sa.Boolean(), nullable=True),
    sa.Column('notifications_02', sa.Boolean(), nullable=True),
    sa.Column('notifications_03', sa.Boolean(), nullable=True),
    sa.Column('notifications_04', sa.Boolean(), nullable=True),
    sa.Column('notifications_05', sa.Boolean(), nullable=True),
    sa.Column('notifications_06', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('online', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paypal_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_request_id', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('vat', sa.Numeric(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('billing_url', sa.String(), nullable=True),
    sa.Column('account_type', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('question_detect_lang', sa.String(), nullable=True),
    sa.Column('editing', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('question_detect_lang', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_user_id', sa.Integer(), nullable=False),
    sa.Column('category_user_name', sa.String(), nullable=False),
    sa.Column('name_hu', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_de', sa.String(), nullable=True),
    sa.Column('name_fr', sa.String(), nullable=True),
    sa.Column('name_es', sa.String(), nullable=True),
    sa.Column('description_hu', sa.String(), nullable=True),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('description_de', sa.String(), nullable=True),
    sa.Column('description_fr', sa.String(), nullable=True),
    sa.Column('description_es', sa.String(), nullable=True),
    sa.Column('img_data', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('experience_detect_lang', sa.String(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('editing', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talking_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('talking_answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_detect_lang', sa.String(), nullable=True),
    sa.Column('answer_type', sa.String(), nullable=True),
    sa.Column('editing', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talking_answer_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_detect_lang', sa.String(), nullable=True),
    sa.Column('answer_type', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talking_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('experience_detect_lang', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talking_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vote', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('source_data', sa.String(), nullable=True),
    sa.Column('target_data', sa.String(), nullable=True),
    sa.Column('translate_type', sa.String(), nullable=True),
    sa.Column('translate_type_id', sa.Integer(), nullable=True),
    sa.Column('translate_type_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translate_talking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('source_data', sa.String(), nullable=True),
    sa.Column('target_data', sa.String(), nullable=True),
    sa.Column('translate_type', sa.String(), nullable=True),
    sa.Column('translate_type_id', sa.Integer(), nullable=True),
    sa.Column('translate_type_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('privacy', sa.String(), nullable=False),
    sa.Column('deleted', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_billing_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_company', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_tax', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_vat', sa.String(), nullable=True),
    sa.Column('payment_country_vat', sa.String(), nullable=True),
    sa.Column('zip_number', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_shipping_address', sa.String(), nullable=True),
    sa.Column('billingo_partner_id', sa.Numeric(), nullable=True),
    sa.Column('completed', sa.String(), nullable=False),
    sa.Column('last_modification_user_id', sa.Integer(), nullable=True),
    sa.Column('last_modification_user_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_worker', sa.String(), nullable=False),
    sa.Column('is_admin', sa.String(), nullable=False),
    sa.Column('is_admin_settings_management', sa.String(), nullable=False),
    sa.Column('is_user_management', sa.String(), nullable=False),
    sa.Column('is_category_management', sa.String(), nullable=False),
    sa.Column('is_notifications', sa.String(), nullable=False),
    sa.Column('subscribed', sa.String(), nullable=False),
    sa.Column('subscribed_start', sa.DateTime(), nullable=True),
    sa.Column('subscribed_end', sa.DateTime(), nullable=True),
    sa.Column('subscribed_type', sa.Numeric(), nullable=True),
    sa.Column('subscribed_monthly', sa.Numeric(), nullable=True),
    sa.Column('subscribed_ads', sa.Numeric(), nullable=True),
    sa.Column('subscribed_chat', sa.Numeric(), nullable=True),
    sa.Column('inactive_account', sa.String(), nullable=False),
    sa.Column('last_modification_user_id', sa.Integer(), nullable=True),
    sa.Column('last_modification_user_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_secondary_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('secret_key', sa.String(), nullable=True),
    sa.Column('count', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session_history_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('country_name', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('browser_name', sa.String(), nullable=True),
    sa.Column('browser_version', sa.String(), nullable=True),
    sa.Column('os_name', sa.String(), nullable=True),
    sa.Column('platform_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shipping_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zip_number', sa.String(), nullable=True),
    sa.Column('place', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_pdf_relationship',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('animal_pdf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['animal_pdf_id'], ['animal_pdf.id'], )
    )
    op.create_table('animal_photos_relationship',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('animal_photos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['animal_photos_id'], ['animal_photos.id'], )
    )
    op.create_table('animal_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('animal_videos_relationship',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('animal_videos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['animal_videos_id'], ['animal_videos.id'], )
    )
    op.create_table('answers_history_relationship',
    sa.Column('answers_id', sa.Integer(), nullable=True),
    sa.Column('answers_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers_history_id'], ['answers_history.id'], ),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], )
    )
    op.create_table('answers_relationship',
    sa.Column('questions_id', sa.Integer(), nullable=True),
    sa.Column('answers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], )
    )
    op.create_table('barion_payment_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('barion_payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barion_payment_id'], ['barion_payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('messages_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('messages_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('notification_settings_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notification_settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_settings_id'], ['notification_settings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('online_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('online_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['online_id'], ['online.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('paypal_payment_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('paypal_payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paypal_payment_id'], ['paypal_payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('questions_history_relationship',
    sa.Column('questions_id', sa.Integer(), nullable=True),
    sa.Column('questions_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questions_history_id'], ['questions_history.id'], ),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], )
    )
    op.create_table('sub_category_relationship',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], )
    )
    op.create_table('talking_answer_history_relationship',
    sa.Column('talking_answer_id', sa.Integer(), nullable=True),
    sa.Column('talking_answer_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talking_answer_history_id'], ['talking_answer_history.id'], ),
    sa.ForeignKeyConstraint(['talking_answer_id'], ['talking_answer.id'], )
    )
    op.create_table('talking_answer_relationship',
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('talking_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talking_answer_id'], ['talking_answer.id'], ),
    sa.ForeignKeyConstraint(['talking_id'], ['talking.id'], )
    )
    op.create_table('talking_history_relationship',
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('talking_history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talking_history_id'], ['talking_history.id'], ),
    sa.ForeignKeyConstraint(['talking_id'], ['talking.id'], )
    )
    op.create_table('talking_vote_relationship',
    sa.Column('talking_id', sa.Integer(), nullable=True),
    sa.Column('talking_vote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['talking_id'], ['talking.id'], ),
    sa.ForeignKeyConstraint(['talking_vote_id'], ['talking_vote.id'], )
    )
    op.create_table('translate_relationship',
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('translate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['translate_id'], ['translate.id'], )
    )
    op.create_table('translate_talking_relationship',
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('translate_talking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.ForeignKeyConstraint(['translate_talking_id'], ['translate_talking.id'], )
    )
    op.create_table('user_billing_information_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_billing_information_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_billing_information_id'], ['user_billing_information.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_permission_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_permission_id'], ['user_permission.id'], )
    )
    op.create_table('user_profile_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], )
    )
    op.create_table('user_secondary_email_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_secondary_email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_secondary_email_id'], ['user_secondary_email.id'], )
    )
    op.create_table('user_session_history_login_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_session_history_login_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_session_history_login_id'], ['user_session_history_login.id'], )
    )
    op.create_table('user_shipping_information_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_shipping_information_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_shipping_information_id'], ['user_shipping_information.id'], )
    )
    op.create_table('wishlist_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_relationship')
    op.drop_table('user_shipping_information_relationship')
    op.drop_table('user_session_history_login_relationship')
    op.drop_table('user_secondary_email_relationship')
    op.drop_table('user_profile_relationship')
    op.drop_table('user_permission_relationship')
    op.drop_table('user_billing_information_relationship')
    op.drop_table('translate_talking_relationship')
    op.drop_table('translate_relationship')
    op.drop_table('talking_vote_relationship')
    op.drop_table('talking_history_relationship')
    op.drop_table('talking_answer_relationship')
    op.drop_table('talking_answer_history_relationship')
    op.drop_table('sub_category_relationship')
    op.drop_table('questions_history_relationship')
    op.drop_table('paypal_payment_relationship')
    op.drop_table('online_relationship')
    op.drop_table('notification_settings_relationship')
    op.drop_table('messages_relationship')
    op.drop_table('barion_payment_relationship')
    op.drop_table('answers_relationship')
    op.drop_table('answers_history_relationship')
    op.drop_table('animal_videos_relationship')
    op.drop_table('animal_relationship')
    op.drop_table('animal_photos_relationship')
    op.drop_table('animal_pdf_relationship')
    op.drop_table('wishlist')
    op.drop_table('user_shipping_information')
    op.drop_table('user_session_history_login')
    op.drop_table('user_secondary_email')
    op.drop_table('user_profile')
    op.drop_table('user_permission')
    op.drop_table('user_billing_information')
    op.drop_table('user')
    op.drop_table('translate_talking')
    op.drop_table('translate')
    op.drop_table('talking_vote')
    op.drop_table('talking_history')
    op.drop_table('talking_answer_history')
    op.drop_table('talking_answer')
    op.drop_table('talking')
    op.drop_table('sub_category')
    op.drop_table('rating')
    op.drop_table('questions_history')
    op.drop_table('questions')
    op.drop_table('paypal_payment')
    op.drop_table('online')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_host_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('category')
    op.drop_table('barion_payment')
    op.drop_table('answers_history')
    op.drop_table('answers')
    op.drop_table('animal_videos')
    op.drop_table('animal_photos')
    op.drop_table('animal_pdf')
    op.drop_table('animal')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###
